CREATE TABLE IF NOT EXISTS HFR_facilities (
id serial,
commFacName VARCHAR(50),
council VARCHAR(50),
createdAt VARCHAR(50),
district VARCHAR(50),
facIDNumber VARCHAR(50),
facilityType VARCHAR(50),
facilityTypeGroup VARCHAR(50),
latitude FLOAT,
longitude FLOAT,
name VARCHAR(50),
oSchangeClosedtoOperational VARCHAR(50),
oSchangeOpenedtoClose VARCHAR(50),
operatingStatus VARCHAR(50),
ownership VARCHAR(50),
ownershipGroup VARCHAR(50),
postorUpdate VARCHAR(50),
region VARCHAR(50),
registrationStatus VARCHAR(50),
updatedAt VARCHAR(50),
villageMtaa VARCHAR(60),
ward VARCHAR(50),
zone VARCHAR(50),
IlIDNumber VARCHAR(50)
);